ubuntu/android-java-6/24.4.1/Dockerfile
ubuntu/android-java-7/24.4.1/Dockerfile
ubuntu/android-java-8/24.4.1/Dockerfile
ubuntu/docker/1.12.1/Dockerfile
ubuntu/docker/17.09.0/Dockerfile
ubuntu/docker/17.09.0/dockerd-entrypoint.sh
ubuntu/dot-net/core-1/Dockerfile
ubuntu/golang/1.5.4/Dockerfile
ubuntu/golang/1.6.3/Dockerfile
ubuntu/golang/1.7.3/Dockerfile
ubuntu/java/openjdk-6/Dockerfile
ubuntu/java/openjdk-7/Dockerfile
ubuntu/nodejs/4.3.2/Dockerfile
ubuntu/nodejs/4.4.7/Dockerfile
ubuntu/nodejs/5.12.0/Dockerfile
ubuntu/nodejs/6.3.1/Dockerfile
ubuntu/nodejs/7.0.0/Dockerfile
ubuntu/python/2.7.12/Dockerfile
ubuntu/python/3.3.6/Dockerfile
ubuntu/python/3.4.5/Dockerfile
ubuntu/python/3.5.2/Dockerfile
ubuntu/ruby/2.1.10/Dockerfile
ubuntu/ruby/2.2.5/Dockerfile
ubuntu/ruby/2.3.1/Dockerfile
ubuntu/ubuntu-base/14.04/Dockerfile

Updating CLI in curated Images
Pinning Images to specific versions

Adding Docker 17 to Curated Images

---

ubuntu/docker/17.09.0/Dockerfile

Remove duplicate line from ubuntu/docker/17.09.0/Dockerfile

Remove duplicate line from ubuntu/docker/17.09.0/Dockerfile

---

local_builds/codebuild_build.sh

Change to bash

---

Makefile

Description of changes:
Added proxy option to docker build.

chore: Add proxy setting when docker build.

---

local_builds/codebuild_build.sh

Add support for running local agent on Windows

Add support for running local agent on Windows

---

local_builds/codebuild_build.sh

Reverts aws/aws-codebuild-docker-images#301

Revert "directly assigned buildspec path to docker command outside of path ch…"

---

README.md
al2/x86_64/standard/3.0/Dockerfile
al2/x86_64/standard/3.0/amazon-ssm-agent.json
al2/x86_64/standard/3.0/dockerd-entrypoint.sh
al2/x86_64/standard/3.0/runtimes.yml
al2/x86_64/standard/3.0/ssh_config
al2/x86_64/standard/3.0/tools/android-accept-licenses.sh
al2/x86_64/standard/3.0/tools/runtime_configs/php/7.3.12
al2/x86_64/standard/3.0/tools/runtime_configs/php/7.3.13
al2/x86_64/standard/3.0/tools/runtime_configs/php/7.4.0
al2/x86_64/standard/3.0/tools/runtime_configs/php/7.4.1
al2/x86_64/standard/3.0/tools/runtime_configs/python/3.7.4
al2/x86_64/standard/3.0/tools/runtime_configs/python/3.7.6
al2/x86_64/standard/3.0/tools/runtime_configs/python/3.8.0
al2/x86_64/standard/3.0/tools/runtime_configs/python/3.8.1
ubuntu/standard/4.0/Dockerfile
ubuntu/standard/4.0/amazon-ssm-agent.json
ubuntu/standard/4.0/dockerd-entrypoint.sh
ubuntu/standard/4.0/runtimes.yml
ubuntu/standard/4.0/ssh_config
ubuntu/standard/4.0/tools/android-accept-licenses.sh
ubuntu/standard/4.0/tools/runtime_configs/php/7.3.12
ubuntu/standard/4.0/tools/runtime_configs/php/7.3.13
ubuntu/standard/4.0/tools/runtime_configs/php/7.4.0
ubuntu/standard/4.0/tools/runtime_configs/php/7.4.1
ubuntu/standard/4.0/tools/runtime_configs/python/3.7.4
ubuntu/standard/4.0/tools/runtime_configs/python/3.7.6
ubuntu/standard/4.0/tools/runtime_configs/python/3.8.0
ubuntu/standard/4.0/tools/runtime_configs/python/3.8.1

Add new image versions: Standard 4.0, AL2 3.0

---

al2/x86_64/standard/3.0/Dockerfile
al2/x86_64/standard/3.0/tools/runtime_configs/python/3.7.6
al2/x86_64/standard/3.0/tools/runtime_configs/python/3.8.1
ubuntu/standard/4.0/Dockerfile
ubuntu/standard/4.0/tools/runtime_configs/python/3.7.6
ubuntu/standard/4.0/tools/runtime_configs/python/3.8.1

Update Standard 4.0, AL2 3.0 images with python --enable-shared flag

Update Standard 4.0, AL2 3.0 with python --enable-shared flag

---

local_builds/README.md
local_builds/codebuild_build.sh

Add option for supporting privileged build container

---

al2/x86_64/standard/1.0/legal/THIRD_PARTY_LICENSES.txt
al2/x86_64/standard/1.0/legal/bill_of_material.txt
al2/x86_64/standard/2.0/legal/THIRD_PARTY_LICENSES.txt
al2/x86_64/standard/2.0/legal/bill_of_material.txt
al2/x86_64/standard/3.0/legal/THIRD_PARTY_LICENSES.txt
al2/x86_64/standard/3.0/legal/bill_of_material.txt
ubuntu/standard/1.0/legal/THIRD_PARTY_LICENSES.txt
ubuntu/standard/1.0/legal/bill_of_material.txt
ubuntu/standard/2.0/legal/THIRD_PARTY_LICENSES.txt
ubuntu/standard/2.0/legal/bill_of_material.txt
ubuntu/standard/3.0/legal/THIRD_PARTY_LICENSES.txt
ubuntu/standard/3.0/legal/bill_of_material.txt
ubuntu/standard/4.0/legal/THIRD_PARTY_LICENSES.txt
ubuntu/standard/4.0/legal/bill_of_material.txt

Add Linux standard images legal files

---

al2/aarch64/standard/1.0/Dockerfile
al2/aarch64/standard/1.0/amazon-ssm-agent.json
al2/aarch64/standard/2.0/Dockerfile
al2/aarch64/standard/2.0/amazon-ssm-agent.json
al2/aarch64/standard/2.0/dockerd-entrypoint.sh
al2/aarch64/standard/2.0/legal/THIRD_PARTY_LICENSES.txt
al2/aarch64/standard/2.0/legal/bill_of_material.txt
al2/aarch64/standard/2.0/runtimes.yml
al2/aarch64/standard/2.0/ssh_config
al2/aarch64/standard/2.0/tools/runtime_configs/php/7.3.19
al2/aarch64/standard/2.0/tools/runtime_configs/php/7.4.7
al2/aarch64/standard/2.0/tools/runtime_configs/python/3.7.7
al2/aarch64/standard/2.0/tools/runtime_configs/python/3.8.3
al2/x86_64/standard/3.0/tools/runtime_configs/php/7.3.19
al2/x86_64/standard/3.0/tools/runtime_configs/php/7.4.7
al2/x86_64/standard/3.0/tools/runtime_configs/python/3.8.3
ubuntu/standard/4.0/Dockerfile
ubuntu/standard/4.0/tools/runtime_configs/php/7.3.19
ubuntu/standard/4.0/tools/runtime_configs/php/7.4.7
ubuntu/standard/4.0/tools/runtime_configs/python/3.8.3

Update Linux and ARM Dockerfiles

---

al2/x86_64/standard/2.0/Dockerfile
al2/x86_64/standard/3.0/Dockerfile
ubuntu/standard/3.0/Dockerfile
ubuntu/standard/4.0/Dockerfile

Fix GeckoDriver download issue

---

al2/aarch64/standard/1.0/Dockerfile
al2/aarch64/standard/2.0/Dockerfile
al2/x86_64/standard/2.0/Dockerfile
al2/x86_64/standard/3.0/Dockerfile
ubuntu/standard/3.0/Dockerfile
ubuntu/standard/4.0/Dockerfile

Golang version upgrade and SSM agent update.

---

local_builds/README.md
local_builds/codebuild_build.sh

Issue #, if available:  #337 
Description of changes: Add option for supporting test reports.

Add option for supporting test reports

---

local_builds/README.md

Update documentation URL for SHA hash

---

al2/x86_64/standard/3.0/Dockerfile

Small change that I noticed while browsing the Dockerfile.

Align the comment with the real version

---

README.md
al2/x86_64/standard/4.0/Dockerfile
ubuntu/standard/6.0/Dockerfile

Update readme with standard 6.0 and al2 standard 4.0

Update readme with new image versions

---

al2/aarch64/standard/3.0/Dockerfile
al2/aarch64/standard/3.0/amazon-ssm-agent.json
al2/aarch64/standard/3.0/dockerd-entrypoint.sh
al2/aarch64/standard/3.0/legal/THIRD_PARTY_LICENSES.txt
al2/aarch64/standard/3.0/legal/bill_of_material.txt
al2/aarch64/standard/3.0/runtimes.yml
al2/aarch64/standard/3.0/ssh_config
al2/aarch64/standard/3.0/tools/runtime_configs/python/3.11.2

Releas arm standard 3.0

---

al2/x86_64/standard/corretto11/Dockerfile
al2/x86_64/standard/corretto8/Dockerfile

fix entrypoint for corretto images

---

al2/x86_64/standard/4.0/Dockerfile
al2/x86_64/standard/4.0/legal/THIRD_PARTY_LICENSES.txt
al2/x86_64/standard/5.0/Dockerfile
al2/x86_64/standard/5.0/legal/THIRD_PARTY_LICENSES.txt
ubuntu/standard/5.0/Dockerfile
ubuntu/standard/6.0/Dockerfile
ubuntu/standard/7.0/Dockerfile

Update Supported Images-Switch to North America stunnel repo

---

al2/aarch64/standard/2.0/Dockerfile
al2/aarch64/standard/2.0/legal/THIRD_PARTY_LICENSES.txt
al2/aarch64/standard/3.0/Dockerfile
al2/aarch64/standard/3.0/legal/THIRD_PARTY_LICENSES.txt

Update stunnel url

---

al2/x86_64/standard/4.0/Dockerfile
al2/x86_64/standard/5.0/Dockerfile
ubuntu/standard/6.0/Dockerfile
ubuntu/standard/7.0/Dockerfile

- Upgrade .Net versions to resolve CVE-2024-21386 and CVE-2024-21404

upgrade .Net versions to address security issues

---

al2/aarch64/standard/2.0/Dockerfile
al2/aarch64/standard/3.0/Dockerfile

- upgrade runc and .Net package versions to address various CVEs

upgrade runc and .Net packages on Arm images

---

al2/aarch64/standard/2.0/Dockerfile
ubuntu/standard/5.0/Dockerfile

Upgrade ssm agent version to address CVEs,

upgrade ssm agent version

---

al/aarch64/standard/2.0/Dockerfile

Apply arm image updates.
