aws/aws-codebuild-docker-images

- ubuntu/android-java-6/24.4.1/Dockerfile
- ubuntu/android-java-7/24.4.1/Dockerfile
- ubuntu/android-java-8/24.4.1/Dockerfile
- ubuntu/docker/1.12.1/Dockerfile
- ubuntu/docker/17.09.0/Dockerfile
- ubuntu/dot-net/core-1/Dockerfile
- ubuntu/dot-net/core-2/Dockerfile
- ubuntu/golang/1.5.4/Dockerfile
- ubuntu/golang/1.6.3/Dockerfile
- ubuntu/golang/1.7.3/Dockerfile
- ubuntu/java/openjdk-6/Dockerfile
- ubuntu/java/openjdk-7/Dockerfile
- ubuntu/java/openjdk-8/Dockerfile
- ubuntu/nodejs/4.3.2/Dockerfile
- ubuntu/nodejs/4.4.7/Dockerfile
- ubuntu/nodejs/5.12.0/Dockerfile
- ubuntu/nodejs/6.3.1/Dockerfile
- ubuntu/nodejs/7.0.0/Dockerfile
- ubuntu/python/2.7.12/Dockerfile
- ubuntu/python/3.3.6/Dockerfile
- ubuntu/python/3.4.5/Dockerfile
- ubuntu/python/3.5.2/Dockerfile
- ubuntu/ruby/2.1.10/Dockerfile
- ubuntu/ruby/2.2.5/Dockerfile
- ubuntu/ruby/2.3.1/Dockerfile
- ubuntu/ubuntu-base/14.04/Dockerfile
trusty-security has pushed updated version 5.5.59 to fix security issues
CVE-2018-2562, CVE-2018-2622, CVE-2018-2640, CVE-2018-2665, CVE-2018-2668
Closes: #30
> Update libmysqlclient-dev to 5.5.59

- ubuntu/golang/1.10/Dockerfile
- ubuntu/golang/1.7.3/Dockerfile
Fixes #38
Changes:
- Add execution permissions to `dep` in `aws/codebuild/golang:1.7.3` image.
- Add execution permissions to `dep` in `aws/codebuild/golang:1.10` image.
> Add execution permissions to dep

- ubuntu/android-java-8/24.4.1/Dockerfile
- ubuntu/docker/17.09.0/Dockerfile
- ubuntu/dot-net/core-1/Dockerfile
- ubuntu/dot-net/core-2/Dockerfile
- ubuntu/golang/1.10/Dockerfile
- ubuntu/golang/1.7.3/Dockerfile
- ubuntu/java/openjdk-8/Dockerfile
- ubuntu/java/openjdk-9/Dockerfile
- ubuntu/nodejs/4.3.2/Dockerfile
- ubuntu/nodejs/4.4.7/Dockerfile
- ubuntu/nodejs/6.3.1/Dockerfile
- ubuntu/php/5.6/Dockerfile
- ubuntu/php/7.0/Dockerfile
- ubuntu/python/2.7.12/Dockerfile
- ubuntu/python/3.3.6/Dockerfile
- ubuntu/python/3.4.5/Dockerfile
- ubuntu/python/3.5.2/Dockerfile
- ubuntu/ruby/2.2.5/Dockerfile
- ubuntu/ruby/2.3.1/Dockerfile
- ubuntu/ubuntu-base/14.04/Dockerfile
It looks like libpq-dev=9.3.21-* does not exist.  Updating to an available patch version.
> updated libpq-dev so that images build correctly

- ubuntu/java/openjdk-8/Dockerfile
This fixes the build for the openjdk8 image. A new java build was done in the PPA a few days ago, see #47
> Fix #47, updating package version for openjdk8.

- ubuntu/docker/17.09.0/Dockerfile
* Update libmysqlclient-dev in ubuntu/docker/17.09.0 to libmysqlclient-dev=5.5.60-*. libmysqlclient-dev=5.5.59-* is not available anymore and causes the docker build to fail.
Haven't tested this beyond getting it to build.
*To Reproduce*
```
cd ubuntu/docker/17.09.0
docker build -t codebuild .
```
> Update libmysqlclient-dev in ubuntu/docker/17.09.0

- ubuntu/nodejs/6.3.1/Dockerfile
x.59 missing from Ubuntu Trusty Repo so image will not build in Docker
Updated to 5.5.60
> update libmysqlclient-dev to 5.5.60

- ubuntu/java/openjdk-8/Dockerfile
Attempting to build this image currently produces the error:
> E: Version '8u162-b12-1~14.04' for 'openjdk-8-jdk' was not found
Looks like the ubuntu version of java8 has been updated again. This has happened before in issue #47.
This PR updates the openjdk to the availabile build version stated here: https://launchpad.net/~openjdk-r/+archive/ubuntu/ppa
> update openjdk8 version to 8u171-b11-2

- ubuntu/golang/1.10/Dockerfile
When trying to build the Docker image locally (with latest branch), I get the following message:
> The following packages have unmet dependencies:
libpq-dev : Depends: libpq5 (= 9.3.22-0ubuntu0.14.04) but 9.3.23-0ubuntu0.14.04 is to be installed
E: Unable to correct problems, you have held broken packages.
Updating `libpq-dev-9.3.22` to `libpq-dev-9.3.23` solved the issue and the Docker image can now be built locally.
> Updating to libpq-dev-9.3.23.

- ubuntu/nodejs/10.1.0/Dockerfile
- ubuntu/nodejs/6.3.1/Dockerfile
- ubuntu/nodejs/8.11.0/Dockerfile
Since CodeBuild executes all commands as root, it makes things easier and
less surprising to users if unsafe-perm is enabled in ~/.npmrc, as otherwise
npm may have surprising behavior, in particular around running `npm pack`
and similar commands, which will emit a warning that scripts will not be run
if unsafe-perm is not set, and proceed to return as if everything was
successfully done.
*Description of changes:* Enables `unsafe-perm` NPM setting, which allows executing a number of commands as `root` without possibly surprising behavior.
> Turn on NPM's unsafe-perm setting

- local_builds/codebuild_build.sh
* [Issue 121](https://github.com/aws/aws-codebuild-docker-images/issues/121)
* This change fixes an issue with environment variables file path containing spaces (e.g. if you store files in a "/Users/user/Google Drive/project" directory).
* Encapsulating paths in quotes, so that spaces are correctly parsed
*Testing:*
I tested it locally and it works with both
* Absolute path for the environment variables, e.g. "/Users/user1/Google Drive/project/vars.env"
* Relative path, e.g. "vars.env" (will correctly resolve the working directory to absolute path even if it has spaces)
> Issue 121: Fixing an issue with spaces in environment variables file path

- ubuntu/ruby/2.5.3/Dockerfile
- ubuntu/ruby/2.5.3/dockerd-entrypoint.sh
#133
This is the latest release of Ruby which includes a couple of fixes for security vulnerabilities:
* [CVE-2018-16396: Tainted flags are not propagated in `Array#pack` and `String#unpack` with some directives][1]
* [CVE-2018-16395: `OpenSSL::X509::Name` equality check does not work correctly][2]
See the release notes for [v2.5.2][3] and [v2.5.3][4] for more details.
Note that I did this by copying the files from the `ubuntu/ruby/2.5.1` directory and updating the following environment variable values:
* `RUBY_VERSION`
* `RUBY_DOWNLOAD_SHA256`
* `RUBYGEMS_VERSION`
* `BUNDLER_VERSION`
You can see the output from building and running the image in [this Gist][5].
[1]: https://www.ruby-lang.org/en/news/2018/10/17/not-propagated-taint-flag-in- …
> Add Ruby v2.5.3

- Makefile
- README.md
This change introduces a GNU Makefile so that users of this repository can build all docker images locally by typing `make` or a particular image by typing a command like `make ruby/2.3.1`. I did this for myself as the Linux-based computer that I need to run build testing from can't run the buildspec.yml file, but it can run a Makefile no sweat.
The Makefile rather haphazardly pulls from the `buildspec.yaml` to obtain the list of build targets. I implemented an additional `all` target which allows a user to build all of the images in one shot if they feel the need. The user could also potentially speed up their build by typing `make all -j NUMCONCURRENTBUILDS`, but I can't support that claim with any data - it's just an interesting observation of mine.
By …
> GNU Makefile so that all images can be built by typing, for example, make ruby/2.3.1

- ubuntu/python/3.7.1/Dockerfile
https://github.com/aws/aws-codebuild-docker-images/issues/169
Python 3.7.1 is not able to build on MacOS due to the keyserver timed out. I have tested this change against both MacOS and Linux. It should be backwards compatible.
> Fix python build failure on Mac

- local_builds/README.md
- local_builds/codebuild_build.sh
> Add option for secondary sources

- ubuntu/golang/1.11/Dockerfile
https://github.com/aws/aws-codebuild-docker-images/issues/202
Adds -y flag to add-apt-repository
> [#202] Unable to build aws/codebuild/golang/1.11 noninteractively

- ubuntu/standard/2.0/Dockerfile
*Issue #, if available:* N/A
*Description of changes:* I was having trouble building the `ubuntu/standard/2.0` image behind a firewall. When the Python GPG key is received, it tries to use a port 80 (HTTP) server first:
https://github.com/aws/aws-codebuild-docker-images/blob/d5a24df151c2e8b967532aa1926278e635bb3a1f/ubuntu/standard/2.0/Dockerfile#L152
This modifies the PHP part to use the same server, which unblocked the build. Might be useful for some other consumers in the future? If not, feel free to close the PR.
(I've left trailing whitespace as is, since #192 addresses that, but merging that PR would much appreciated for people who's editors are set up to work with whitespace-sensitive languages :) )
---
By submitting this pull request, I confirm that you can use, modify, copy, and …
> Use port 80 (HTTP) for PHP GPG key reception

- ubuntu/standard/2.0/Dockerfile
pyyaml did not install cleanly on build because there was no
`bdist_wheel` command found.  To fix this, we just need to make sure to
install the `wheel` package so that `bdist_wheel` can be run for needed
packages.
Added pip installation of upgraded setuptools and wheel to allow pyyaml to install cleanly.
> bugfix:  fixes installation of pyyaml

- ubuntu/standard/2.0/Dockerfile
awscli depends on pyyaml which has a `bdist_wheel` install.  In order to
use `bdist_wheel` the `wheel` package has to be installed.  Sorry for
missing this earlier @Sabin Mathews!
When running docker build, there will be a failure of the installation of pyyaml because pip installation of pyyaml requires `bdist_wheel`.  `bdist_wheel` was removed from setuptools and moved to a separate pip package `wheel`.  
> bugfix:  another instance where we need to install wheel

- ubuntu/standard/2.0/Dockerfile
https://github.com/aws/aws-codebuild-docker-images/issues/223
Updates apt-add-repository with `-y` flag for noninteractive building.
> Ubuntu 2.0 does not build noninteractively

- ubuntu/standard/2.0/Dockerfile
This PR adds a linebreak character that is missing on this line, preventing the Dockerfile from being run due to a parsing error:
```
Error response from daemon: Dockerfile parse error line 112: unknown instruction: &&
```
> Fix linebreak syntax error in Dockerfile

- al2/x86_64/standard/2.0/Dockerfile
- al2/x86_64/standard/2.0/dockerd-entrypoint.sh
- al2/x86_64/standard/2.0/runtimes.yml
- al2/x86_64/standard/2.0/ssh_config
- al2/x86_64/standard/2.0/tools/android-accept-licenses.sh
- ubuntu/standard/3.0/Dockerfile
- ubuntu/standard/3.0/dockerd-entrypoint.sh
- ubuntu/standard/3.0/runtimes.yml
- ubuntu/standard/3.0/ssh_config
- ubuntu/standard/3.0/tools/android-accept-licenses.sh
New image versions :: AL2 2.0 & Standard 3.0
> New image versions :: AL2 2.0 & Standard 3.0

- ubuntu/standard/3.0/Dockerfile
N/A
* stunnel upstream removed the originally used 5.55 from their
official downloads section, breaking the docker build.
> Update ubuntu/standard/3.0 to use stunnel 5.56

- al2/aarch64/standard/1.0/Dockerfile
- al2/x86_64/standard/1.0/Dockerfile
- al2/x86_64/standard/2.0/Dockerfile
- al2/x86_64/standard/3.0/Dockerfile
- ubuntu/standard/1.0/Dockerfile
- ubuntu/standard/2.0/Dockerfile
- ubuntu/standard/3.0/Dockerfile
- ubuntu/standard/4.0/Dockerfile
ref. [Amazon S3 Path Deprecation Plan – The Rest of the Story](https://aws.amazon.com/jp/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/)
As you know, path-style S3 url is now deprecated.
So, we should use virtual-hosted style url instead of it.
The document for [Installing the Amazon ECS CLI](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_installation.html) is alread updated,
and uses virtual-hosted style url now.
> For Linux systems:
> sudo curl -o /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
> use virtual-hosted style url instead of path-style

- ubuntu/standard/4.0/runtimes.yml
*Issue #, if available:* N/A
Using docker 18 in the standard:4.0 image runtime hopefully no longer lies to people about being version 19.
> Fixes docker version number typo

- ubuntu/standard/2.0/Dockerfile
*Issue #340*
This PR updates the `RUN` command in the `Dockerfile` to use `jq` to isolate the latest 64bit Linux release of `geckodriver`. This is reliable in cases where the formatting of the JSON response from the GitHub API changes and avoids the use of `grep` / `cut` / `tr`.
> Fix geckodriver download

- local_builds/codebuild_build.sh
Issue: https://github.com/aws/aws-codebuild-docker-images/issues/284
Update script to use alternative local agent image name if provided as CLI argument. This change is required to allow use of the local agent image tagged with :aarch64 instead of :latest
> Update codebuild_build.sh to use local image name override

- local_builds/README.md
https://github.com/aws/aws-codebuild-docker-images/issues/284
> Update README.md for aarch64 local agent image

- local_builds/codebuild_build.sh
Add quotes in if statement around `$local_agent_image`. Matches formatting in the rest of the script and gives expected behavior.
This script was running as expected yesterday but after re-downloading it I was getting an error that said `"docker run" requires at least 1 argument.` This change returns the script to expected behavior when running without the `-l` flag
> Add quotes around local_agent_image

- al2/aarch64/standard/2.0/tools/runtime_configs/python/3.7.7
- al2/aarch64/standard/2.0/tools/runtime_configs/python/3.8.3
- al2/x86_64/standard/2.0/tools/runtime_configs/python/3.7.10
- al2/x86_64/standard/2.0/tools/runtime_configs/python/3.8.8
- al2/x86_64/standard/3.0/tools/runtime_configs/python/3.7.10
- al2/x86_64/standard/3.0/tools/runtime_configs/python/3.8.8
- ubuntu/standard/3.0/tools/runtime_configs/python/3.7.10
- ubuntu/standard/3.0/tools/runtime_configs/python/3.8.8
- ubuntu/standard/4.0/tools/runtime_configs/python/3.7.10
- ubuntu/standard/4.0/tools/runtime_configs/python/3.8.8
- ubuntu/standard/5.0/tools/runtime_configs/python/3.7.10
- ubuntu/standard/5.0/tools/runtime_configs/python/3.8.8
- ubuntu/standard/5.0/tools/runtime_configs/python/3.9.2
- unsupported_images/al2/x86_64/standard/1.0/tools/runtime_configs/python/3.7.6
- unsupported_images/al2/x86_64/standard/1.0/tools/runtime_configs/python/3.8.1
- unsupported_images/ubuntu/standard/1.0/tools/runtime_configs/python/3.7.6
- unsupported_images/ubuntu/standard/1.0/tools/runtime_configs/python/3.8.1
- unsupported_images/ubuntu/standard/2.0/tools/runtime_configs/python/3.7.6
- unsupported_images/ubuntu/standard/2.0/tools/runtime_configs/python/3.8.1
*Issue #, if available:* #460
[pyenv 2.0.0](https://github.com/pyenv/pyenv/blob/master/CHANGELOG.md#release-200) removed ldflags_dirs as it "is not needed for Python and causes failures". The python runtime config files use the outdated calls. This pull request removes all references to `ldflags_dirs`. Now it is possible to build the images again.
> Remove ldflags_dirs step. Fixes #460

- ubuntu/standard/5.0/Dockerfile
Blog post on July 2021 Security Releases: nodejs.org/en/blog/vulnerability/july-2021-security-releases
bump node 14.x to latest 14.17.2
> chore: bump node 14.x to latest 14.17.2

- ubuntu/standard/5.0/Dockerfile
- ubuntu/standard/5.0/tools/runtime_configs/php/7.3.25
- ubuntu/standard/5.0/tools/runtime_configs/php/7.4.13
- ubuntu/standard/5.0/tools/runtime_configs/php/8.0.0
Both Debian 10 and latest Mac OS X have PHP with sodium extension compiled in - https://www.php.net/manual/en/sodium.installation.php
When you run composer update locally it sees that the extension is available and builds the dependencies around it. However, when you deploy with Codebuild the extension is no longer available and it is hard to install it since during deployment since there is no package available for it. I believe the package maintainers assume it is already bundled in so no package is required.
> Enable sodium for PHP since it should be bundled by default as of PHP 7.2.0

- ubuntu/standard/5.0/Dockerfile
- ubuntu/standard/5.0/runtimes.yml
*Issue #, if available:* closes #425
`aws/codebuild/standard:5.0` image changes
- Add support for `golang: 1.16`
- Bump go 1.15 to latest version `1.15.12`
> standard:5.0 Golang version 1.16 support and bump to 1.15.12

- al2/aarch64/standard/2.0/Dockerfile
This fixes an issue with the **PowerShell Core** installation, as an empty continuation line at the end of the **JAVA** install block was messing with `ENV POWERSHELL_VERSION` being set.
Adds the `&& yum clean all` present in the AL2 x86_64 image.
> Add missing `yum clean all` to JAVA install block in AL2 (ARM) (Fixes PowerShell Install)

- al2/aarch64/standard/2.0/Dockerfile
ECR Helper: https://github.com/awslabs/amazon-ecr-credential-helper
This brings the additions from #370 to `aws/codebuild/amazonlinux2-aarch64-standard:2.0` as well.
> Add ECR Helper for AL2 (ARM)

- README.md
without the full path, when following the steps you get:
~/tmp/codebuild6
❯ cd ubuntu/standard/6.0
cd: no such file or directory: ubuntu/standard/6.0
> Fixed path in docker build steps

- al2/x86_64/standard/4.0/Dockerfile
*Issue #567
https://github.com/aws/aws-codebuild-docker-images/issues/567
Added `java-17-amazon-corretto-devel` which allows for javac to be used out of the box.
This seems like a common functionality which should be included by default.
> added javac into al4:0

- al2/aarch64/standard/1.0/Dockerfile
- al2/aarch64/standard/2.0/Dockerfile
- al2/x86_64/standard/3.0/Dockerfile
- al2/x86_64/standard/4.0/Dockerfile
- ubuntu/standard/4.0/Dockerfile
- ubuntu/standard/5.0/Dockerfile
- ubuntu/standard/6.0/Dockerfile
N/A
Download from archive.apache.org just like ant.
The maven link as is has died and must be updated or pointed to the archive. To allow the build to work as is, I have updated it to use archive.apache.org just like the ant install.
> use archive.apache.org for maven downloads

- ubuntu/standard/7.0/Dockerfile
This will fix #625 
Add docker-buildx binary, which has been removed from docker-cli in 23.0.0
> Add Docker buildx tool to standard:7.0

- README.md
- al2/x86_64/standard/4.0/tools/runtime_configs/php/8.1.18
- al2/x86_64/standard/5.0/Dockerfile
- al2/x86_64/standard/5.0/amazon-ssm-agent.json
- al2/x86_64/standard/5.0/dockerd-entrypoint.sh
- al2/x86_64/standard/5.0/legal/THIRD_PARTY_LICENSES.txt
- al2/x86_64/standard/5.0/legal/bill_of_material.txt
- al2/x86_64/standard/5.0/runtimes.yml
- al2/x86_64/standard/5.0/ssh_config
- al2/x86_64/standard/5.0/tools/runtime_configs/php/8.2.5
- al2/x86_64/standard/5.0/tools/runtime_configs/python/3.11.2
- buildspec.yml
- ubuntu/standard/5.0/Dockerfile
- ubuntu/standard/5.0/tools/runtime_configs/php/8.0.28
- ubuntu/standard/6.0/Dockerfile
- ubuntu/standard/6.0/tools/runtime_configs/php/8.1.18
- ubuntu/standard/6.0/tools/runtime_configs/python/3.10.10
- ubuntu/standard/7.0/Dockerfile
- ubuntu/standard/7.0/tools/runtime_configs/php/8.2.5
> Add al2/x86_64/standard/5.0, update supported images

- al2/x86_64/standard/4.0/Dockerfile
- al2/x86_64/standard/5.0/Dockerfile
- al2/x86_64/standard/corretto11/Dockerfile
- al2/x86_64/standard/corretto8/Dockerfile
- ubuntu/standard/5.0/Dockerfile
- ubuntu/standard/6.0/Dockerfile
- ubuntu/standard/7.0/Dockerfile
- Updated the runc package to resolve CVE-2024-21626
- Upgraded .Net versions to address CVE-2024-0056, CVE-2024-0057 and CVE-2024-21319
> update runc and upgrade .Net versions on Ubuntu and AL(x86_64) images

- al-lambda/aarch64/dotnet8/Dockerfile
- al-lambda/aarch64/dotnet8/legal/bill_of_material.txt
- al-lambda/x86_64/dotnet8/Dockerfile
- al-lambda/x86_64/dotnet8/legal/bill_of_material.txt
> add x86_64/aarch64 dotnet8
